<h1>Update Car</h1>

<hr>

<form action="/cars/<?=$car->getId()?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label for="make">Make:</label>
        <input id="make" type="text" required name="car[make]" value="<?=htmlspecialchars($car->getMake())?>">
        <?php if (!empty($errors)) : ?>
            <div style="color: red"><span><?=$errors['make']?></span></div>
        <?php endif; ?>
    </div>
    <div>
        <label for="model">Email:</label>
        <input id="model" type="text" required name="car[model]" value="<?=htmlspecialchars($car->getModel())?>">
        <?php if (!empty($errors)) : ?>
            <div style="color: red"><span><?=$errors['model']?></span></div>
        <?php endif; ?>
    </div>
    <input type="submit" value="Update">
</form>

