<h1>Users</h1>

<?php
    if (!empty($flash)) :
        foreach ($flash as $s => $messages) :
            foreach ($messages as $m) :
?>
<span style="color: <?php echo $s === 'success' ? 'green' : 'red' ?>"><?=$m?></span>
<br>
<?php
            endforeach;
        endforeach;
    endif;
?>

<hr>

<form action="/users" method="get">
    <input type="search" name="u">
    <input type="submit" value="Search">
</form>

<hr>

<ul>
    <?php foreach ($users as $user) : ?>
        <li><i><?=htmlspecialchars($user['nickname'])?> (<?=htmlspecialchars($user['id'])?>)</i></li>
    <?php endforeach; ?>
</ul>
