<h1>New User</h1>

<hr>

<form action="/users" method="post">
    <div>
        <label for="user[nickname]">Nickname:</label>
        <input type="text" required name="user[nickname]" value="<?=!empty($data) ? $data['nickname'] : ''?>">
        <?php if (!empty($errors)) : ?>
            <div style="color: red"><span><?=$errors['nickname']?></span></div>
        <?php endif; ?>
    </div>
    <div>
        <label for="user[email]">Email:</label>
        <input type="email" required name="user[email]" value="<?=!empty($data) ? $data['email'] : ''?>">
        <?php if (!empty($errors)) : ?>
            <div style="color: red"><span><?=$errors['email']?></span></div>
        <?php endif; ?>
    </div>
    <input type="submit">
</form>
